# Generated by Django 4.1 on 2023-08-12 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 12)),
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="log_unique"
            ),
        ),
    ]
