# Generated by Django 4.1 on 2023-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="well_known_location",
            field=models.IntegerField(default=0),
        ),
    ]
