# Generated by Django 4.1 on 2023-08-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_log_date_log_log_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
