# Generated by Django 4.1 on 2023-08-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(),
        ),
    ]
