# Generated by Django 4.1 on 2023-08-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_alter_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="abeuser",
            name="is_guest",
            field=models.BooleanField(default=0),
        ),
    ]
