# Generated by Django 4.1 on 2023-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellknownlocation",
            name="location_name",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
