# Generated by Django 4.1 on 2023-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manager", "0002_alter_wellknownlocation_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellknownlocation",
            name="deletibility",
            field=models.BooleanField(default=True),
        ),
    ]
